#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          5

bspc config active_border_color '#5E81AC'
bspc config normal_border_color '#273238'
bspc config focused_border_color '#D8DEE9'
bspc config presel_feedback_color '#273238'
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap -model abnt2 -layout br -variant abnt2
setxkbmap -option caps:swapescape

$HOME/.config/polybar/launch.sh &
picom &
dunst $HOME/.config/dunst/dunstrc &
feh --bg-center $HOME/Pictures/wallpapers/wall.jpg
